[package]
name = "krust-hello-world"
version = "0.1.0"
authors = ["Zhixiang Zhao <matthew@mail.matthew-cloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
